name: Maven tests

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up JDK 17
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven tests, get JaCoCo coverage and fail if coverage has not improved.
        run: |
          
          JVM_FLAGS=(
            "-Xms512m"
            "-Xmx2048m"
            "-XX:+UseG1GC"
            "-XX:MaxGCPauseMillis=200"
            "-XX:+PrintGCDetails"
            "-XX:+TieredCompilation"
            "-XX:+HeapDumpOnOutOfMemoryError"
            "-XX:+UseStringDeduplication"
            # Pirate flag. You just got pirated!
          )

          for flag in "${JVM_FLAGS[@]}"; do
            echo "Running tests with JVM flag: $flag"
            mvn verify -DargLine="@{argLine} $flag"

            if [ $? -ne 0 ]; then
              echo "Tests failed with JVM flag: $flag"
              exit 1
            fi
          
            coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv)
            echo "Coverage for flag $flag: $coverage%"
          
            if (( $(echo "$coverage - $threshold <= $epsilon" | bc -l) )); then
              echo "Coverage has not improved for flag $flag."
              exit 1
            else
              echo "New coverage for flag $flag: $coverage%"
            fi
          done
